### ISSUE TITLE
Running YOLOv3 on Colab 

### ISSUE THREAD

**Issue by phamngocthanhtrung** [BlcaKHat/yolov3-Helmet-Detection#1]
Hi, 
could you have train your custom object successful on google colab ? 
Best Regards

**Comment by BlcaKHat** [comment]
if you have small dataset, you can train but you need to take your backup before 12 hours otherwise all the progress will be lost.
you can take the backup to google drive and and reinitialize the colab session

**Comment by phamngocthanhtrung** [comment]
Hi, 
thank you for your this great information. 
I'm still a beginner by coding with Colab. 
so far i understand is, that the darknet-model is written in C. 
And with which command can i starting the training or just the detection? 
can I after the configuration writing this command line to train yolo ? 
`darknet.exe detector train data/obj.data yolo-obj.cfg darknet53.conv.74 -map`
can you show me how you coding it on Colab? 
it would be very nice 
Thank You! 
Best Regards

**Comment by BlcaKHat** [comment]
you have to use linux commands for in colab... check how to setup everything and then after zip it and upload it to colab. and then extract it.
may be I will write it out next week. 
at first try setting up everything on local machine. if it works fine , upload the same setup to colab and try it.
