### ISSUE TITLE
What is the source of your training dataset?

### ISSUE THREAD

**Issue by SuphanutN** [BlcaKHat/yolov3-Helmet-Detection#11]
Hello @BlcaKHat, what is the source for your helmet dataset? I currently use your custom weight and it seems very good. I wanna try it with yolov4 but with my own dataset from openimage dataset is not quite good as this one. So I wanna know how many pictures you use and what is the source of your dataset.

Thank you

**Comment by BlcaKHat** [comment]
So, the source of my dataset was taken form open-image dataset and real-time data from the use-case i was working on. in my case it was surveillance of a private property. the important thing to observe is we need similar type of dataset from the scenario we are going to use.
example: In my case, the surveillance camera was always on top with an angle around 50~60 from plane. so, i need more dataset with that angle. these things matter.
I took dataset around 6K. I would say, get some real data, make a video, extract the frames with a different angle and add them to dataset. it will help.

**Comment by SuphanutN** [comment]
thank you so much for the explaination
