### ISSUE TITLE
Im getting None as output while running it on test images folder

### ISSUE THREAD

**Issue by rsingh2083** [BlcaKHat/yolov3-Helmet-Detection#12]
Hi,

Please have a look at my project structure : - 

https://ibb.co/fnfKPBn
https://ibb.co/88rjZCB

Im getting None as output for all the images. 
Do I need to install darknet on windows ? But it isnt giving any error regarding missing darknet or any other error for that matter.
OS : Windows10

**Comment by BlcaKHat** [comment]
set the paths in .py file correctly.

**Comment by NirmalJainCM** [comment]
I have been facing the same issue. I have double checked all the paths and all of them are correct. The input loop runs for 6 times so I think that's not the issue. Please help

**Comment by BlcaKHat** [comment]
Can you add the error details to bring more clearity

**Comment by NirmalJainCM** [comment]
![Screenshot (236)](https://user-images.githubusercontent.com/76167210/102508401-597ece80-40ab-11eb-9b1f-59d96cdbe99c.png)
![Screenshot (237)](https://user-images.githubusercontent.com/76167210/102508405-5b489200-40ab-11eb-9f9f-ede7bc132806.png)

This is what i get when i run the program.

**Comment by BlcaKHat** [comment]
how many images have you added ? can you add some common image ?
and check the version of opencv once.

**Comment by NirmalJainCM** [comment]
I have retained the same images and opencv version is 4.0.1

**Comment by BlcaKHat** [comment]
Try 3.6 opencv

________________________________

**Comment by robotaiguy** [comment]
I am having similar issues. I downloaded your weights, names, and cfg files and your sample images and running directly through darknet via ./darknet detector test <data file> <cfg file> <weights file> <image file> 
And the network loads, but there is no prediction on the image

**Comment by BlcaKHat** [comment]
did you check opencv version ?

**Comment by rudrarajurahul** [comment]
Same issue. For opencv 4 as well as opencv 3.4

**Comment by BlcaKHat** [comment]
hey @rudrarajurahul  I will try to compile again with opencv 4. let me see why this issue is persisting.

**Comment by YYC-ZJU** [comment]
the class name in the obj.names is 'helmet', but in the code is 'Helmet'

**Comment by BlcaKHat** [comment]
@ZJU-Yc  updated.
