### ISSUE TITLE
How can you get the helmet training dataset

### ISSUE THREAD

**Issue by FossilDaddy** [BlcaKHat/yolov3-Helmet-Detection#2]
I wonder to know where can I get the helmet training dataset that can be used to YOLOv3
Thanks a lot

**Comment by BlcaKHat** [comment]
you can download a lot of images from google. find some python script, it will do it for you.
or you can download it from openimage library. there are hundred of images. I had images from ATM CCTV. but I can't share that due to company policy.

**Comment by FossilDaddy** [comment]
thanks for your guidance！

**Comment by BlcaKHat** [comment]
@FossilDaddy   try these.
https://github.com/hardikvasa/google-images-download
https://storage.googleapis.com/openimages/web/index.html

**Comment by letarg0** [comment]
Can You put dataset example?
meybe 2 images, trouble with directores, filenames etc.
please improwe this code.
;)

**Comment by BlcaKHat** [comment]
@letarg0  it is not that complex.
put you code and images all there in the same directory. look into helemtdetection_YOLOV3.py and changes all the paths for inputs and outputs folder. you are set to go.!!
