### ISSUE TITLE
How many classes can 'yolov3-obj_2400.weights' detect?

### ISSUE THREAD

**Issue by machengcheng2016** [BlcaKHat/yolov3-Helmet-Detection#3]
Hi,
Is this model 'yolov3-obj_2400.weights' only able to detect helmet? I wonder how many classes can be detected.
The reason I ask this question is if the model 'yolov3-obj_2400.weights' can detect helmet as well as person, we can further judge whether a person is wearing a helmet or not, just like liveness detection.
Thank you!

**Comment by BlcaKHat** [comment]
I made it detect the only helmet. sometimes it may identify a person head as a helmet.
please train you own model if you want a accurate stuff. I build it just for demonstration. it is not a well-optimized model for production.
good luck.

**Comment by machengcheng2016** [comment]
Alright. Thanks man
