### ISSUE TITLE
Error loading net

### ISSUE THREAD

**Issue by malfonsoNeoris** [BlcaKHat/yolov3-Helmet-Detection#4]
hi, my name is manuel.
I'm trying to run the example.
i have downloaded the git repo and the yolo weigs, cfg and names.
Changed the paths to files as your instructions in the readme

when tryng to run, in the readnetfromdarknet i got
Error: Parsing error (Unknown layer type: shortcut) in cv::dnn::darknet::ReadDarknetFromCfgFile, file C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\dnn\src\darknet\darknet_io.cpp, line 503
PS C:\Source\Pruebas Deteccion\yolov3-Helmet-Detection-master>

i have veryfied the file paths.

Opencv 3.4.1
Python is 3.7.4
Windows 10

thanks

**Comment by BlcaKHat** [comment]
Not sure, I am not a big fan of windows. try reinstalling opencv and build darknet

**Comment by malfonsoNeoris** [comment]
thanks for the reply.
i have already solved it. I had opencv 4... but i downgraded to default version.. (problem with another app) and the default was 3.4.1... wich was incompatible with yolo darknet... 3.4.3 and up are compabiles.


I would like to use the mail to ask you something else.
if in addition to a helmet, I would like to continue having some of the classes that the yolo already provides by default, eg person. 
What should I do? Can't I retrain only part of the network?

I need to detect a person and a helmet.. what i am doing, is loading the default yolov3 with coco names and weights, and your trained yolo. First i find persons... and then over the person roi y searh for helmets.

i would like to know how to retain the person detections from the original yolo... so i dont need to run two detector. In fact, i would also want to detect security vest

thanks!

**Comment by BlcaKHat** [comment]
The best way is to collect your data for a particular class and start training it with the original model.
you need to train. you cannot just plug it. it's a BlackBox.
