### ISSUE TITLE
module object has no attribute 'dnn'

### ISSUE THREAD

**Issue by nancyshaji** [BlcaKHat/yolov3-Helmet-Detection#5]
I am geting the following error when I am running this : python Helmet_detection_YOLOV3.py 

Traceback (most recent call last):
  File "Helmet_detection_YOLOV3.py", line 28, in <module>
    net = cv.dnn.readNetFromDarknet(modelConfiguration, modelWeights)
AttributeError: 'module' object has no attribute 'dnn'

My python version is: Python 2.7.9
Cv2 version: 2.4.9.1

**Comment by BlcaKHat** [comment]
Your opencv doesn't seem to be updated. Update that it should work.

Vijay

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
