### ISSUE TITLE
Could not download pre-trained model

### ISSUE THREAD

**Issue by ujjawalcse** [BlcaKHat/yolov3-Helmet-Detection#7]
Hi @BlcaKHat ,
I'm not able to download the model file provided by you. It's showing the model file is in your trash.
Can you share the same on kujjawal94@gmail.com please?
Thanks.

**Comment by BlcaKHat** [comment]
try once again..
or download here,

https://drive.google.com/file/d/16yH9M_ovw0cJG4gVKuXTkz_cwYxJtwAk/view?usp=sharing

dii\d you read my post ?

________________________________

**Comment by BlcaKHat** [comment]
hi Ujjwal the weight file is missing from my drive.
can you please send it to me if have downloaded it previously.
people are looking for that.

**Comment by ujjawalcse** [comment]
Hi @BlcaKHat, I couldn't download the weight file as it was not there.
Thanks.

**Comment by SuphanutN** [comment]
https://drive.google.com/drive/folders/1Z1a5tSdo0wlOxXFwqU7DZzQyNAYjCCuX , here are the weight that I backup earlier.

**Comment by BlcaKHat** [comment]
thanks @SuphanutN
