### ISSUE TITLE
How to get the dataset?

### ISSUE THREAD

**Issue by Sharpiless** [BlcaKHat/yolov3-Helmet-Detection#8]
Thanks for your contribution! But where to download the dataset?

**Comment by BlcaKHat** [comment]
I can't provide om own dataset.
please visit the places like openImage. you can find tons of data.

**Comment by Sharpiless** [comment]
Thank you anyway. I found the data under your suggestion. 

Here is the hyperlink：[https://storage.googleapis.com/openimages/web/visualizer/index.html?set=train&type=detection&c=%2Fm%2F0zvk5](https://storage.googleapis.com/openimages/web/visualizer/index.html?set=train&type=detection&c=%2Fm%2F0zvk5)

**Comment by BlcaKHat** [comment]
I am glad it helps.
