### ISSUE TITLE
how can be put video in input

### ISSUE THREAD

**Issue by zongoalbert** [BlcaKHat/yolov3-Helmet-Detection#9]
i want to use video or streamin the input  and detection helmets ,

**Comment by nancyshaji** [comment]
You could use these weights with darknet compiled and give in video. Or use other opencv video program with yolo weights.

**Comment by zongoalbert** [comment]
@nancyshaji  Thanks for your quick  reply , its possible to edit or add same lines in  `Helmet_detection_YOLOV3.py` to use it for input video , if the answer is yes , could you please write it here , thanks

**Comment by BlcaKHat** [comment]
try this link . 
https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html?highlight=video%20stream
you can add lines to use video instead of image in the same file.
